import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDGoSNKi1wapE1SpHxTc8wNZGGkJ2nQj7s",authDomain:"nexus-transport-2887b.firebaseapp.com",projectId:"nexus-transport-2887b",storageBucket:"nexus-transport-2887b.firebasestorage.app",messagingSenderId:"972915419764",appId:"1:972915419764:web:7d61dfb03bbe56df867f21"};
const $=id=>document.getElementById(id);const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});const today=()=>new Date().toISOString().slice(0,10);const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
let app,auth,db,user=null,unsub=null,syncing=false,active='dashboard';
let state=defaultState();
function defaultState(){return{meta:{version:'2.0',createdAt:new Date().toISOString()},company:{name:'Nexus Business PR',industry:'general',plan:'Starter',phone:'',email:'',address:'',web:'',logo:'',taxRate:11.5,rep:''},clients:[],services:[],team:[],invoices:[],payments:[],cashflow:[],settings:{nextInvoice:1,nextService:1}}}
const industryLabels={general:{service:'Servicio',worker:'Equipo',vehicle:'Recurso'},transport:{service:'Transporte',worker:'Chofer',vehicle:'Unidad'},hvac:{service:'Servicio HVAC',worker:'Técnico',vehicle:'Vehículo'},salon:{service:'Cita',worker:'Estilista',vehicle:'Estación'},handyman:{service:'Trabajo',worker:'Técnico',vehicle:'Herramienta'},cleaning:{service:'Limpieza',worker:'Empleado',vehicle:'Ruta'},construction:{service:'Proyecto',worker:'Personal',vehicle:'Equipo'},mechanic:{service:'Servicio Mecánico',worker:'Mecánico',vehicle:'Unidad móvil'}};
const pages=[['dashboard','Dashboard','Resumen ejecutivo'],['clients','Clientes','Base comercial'],['services','Servicios','Operación diaria'],['team','Equipo','Empleados / choferes / técnicos'],['invoices','Facturación','Facturas y balances'],['payments','Cobros','Pagos recibidos'],['cashflow','Caja','Ingresos y egresos'],['reports','Reportes','PDF corporativos'],['plans','Planes','Modelo SaaS'],['settings','Configuración','Empresa e identidad']];
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function cloud(mode,msg){$('cloudText').textContent=msg; $('cloudDot').style.background=mode==='ok'?'#0e9f6e':mode==='bad'?'#dc2626':'#d97706'}
function boot(){try{app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);cloud('warn','Esperando login')}catch(e){cloud('bad','Firebase no disponible');console.error(e)}bindAuth();onAuthStateChanged(auth,async u=>{user=u;if(u){$('authView').classList.add('hidden');$('appView').classList.remove('hidden');await loadCloud();buildNav();renderAll();}else{$('authView').classList.remove('hidden');$('appView').classList.add('hidden');if(unsub)unsub();}})}
function bindAuth(){$('btnRegister').onclick=async()=>{try{const email=$('authEmail').value.trim(),pass=$('authPass').value; if(!email||!pass) return toast('Email y contraseña requeridos'); const cred=await createUserWithEmailAndPassword(auth,email,pass); state=defaultState();state.company.name=$('authName').value.trim()||'Mi Negocio';state.company.industry=$('authIndustry').value;state.company.email=email; await saveCloud(true);toast('Cuenta creada');}catch(e){toast(e.message)}};$('btnLogin').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('authEmail').value.trim(),$('authPass').value);toast('Bienvenido')}catch(e){toast('Login falló: '+e.message)}};$('btnResetPass').onclick=async()=>{try{const email=$('authEmail').value.trim(); if(!email)return toast('Escribe tu email'); await sendPasswordResetEmail(auth,email);toast('Correo enviado')}catch(e){toast(e.message)}};$('btnLogout').onclick=()=>signOut(auth);$('btnSync').onclick=async()=>{await saveCloud(true);toast('Sincronizado')}}
function ref(){return doc(db,'users',user.uid,'workspace','main')}
async function loadCloud(){cloud('warn','Sincronizando');const snap=await getDoc(ref()); if(snap.exists()) state={...defaultState(),...snap.data()}; else await saveCloud(true); if(unsub)unsub();unsub=onSnapshot(ref(),s=>{if(syncing)return;if(s.exists()){state={...defaultState(),...s.data()};renderAll();cloud('ok','Sincronizado')}},e=>{cloud('bad','Sin permisos');console.error(e)});}
async function saveCloud(force=false){if(!user||!db)return;try{syncing=true;await setDoc(ref(),{...state,updatedAt:serverTimestamp()},{merge:false});localStorage.setItem('nexusBusinessBackup',JSON.stringify(state));cloud('ok','Sincronizado');}catch(e){cloud('bad','Modo local');localStorage.setItem('nexusBusinessBackup',JSON.stringify(state));console.error(e)}finally{setTimeout(()=>syncing=false,300)}}
function mutate(fn){fn();renderAll();saveCloud();}
function buildNav(){const nav=$('nav');nav.innerHTML=pages.map(([id,title])=>`<button class="navbtn ${id===active?'active':''}" data-page="${id}">${icon(id)} ${title}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));}
function icon(id){return{dashboard:'📊',clients:'👥',services:'🧾',team:'🧑‍🔧',invoices:'📄',payments:'💳',cashflow:'💼',reports:'📑',plans:'🚀',settings:'⚙️'}[id]||'•'}
function showPage(id){active=id;pages.forEach(([p,t,h])=>{$(p).classList.toggle('hidden',p!==id);if(p===id){$('pageTitle').textContent=t;$('pageHint').textContent=h}});buildNav();renderAll()}
function labels(){return industryLabels[state.company.industry]||industryLabels.general}
function totals(){const billed=state.invoices.reduce((a,x)=>a+Number(x.total||0),0),paid=state.payments.reduce((a,x)=>a+Number(x.amount||0),0),expenses=state.cashflow.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0),income=state.cashflow.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0);return{billed,paid,income,expenses,pending:billed-paid,net:income-expenses,services:state.services.length,clients:state.clients.length}}
function renderAll(){if(!user)return;$('sideBiz').textContent=state.company.name||'Nexus Business';$('sidePlan').textContent='Plan '+(state.company.plan||'Starter');renderDashboard();renderClients();renderServices();renderTeam();renderInvoices();renderPayments();renderCashflow();renderReports();renderPlans();renderSettings();}
function renderDashboard(){const t=totals();$('dashboard').innerHTML=`<div class="hero"><h3>${esc(state.company.name)}</h3><p class="muted">Sistema SaaS operacional para ${esc((labels().service||'servicios').toLowerCase())}. Datos privados por usuario.</p></div><div class="kpis"><div class="kpi"><span>Facturado</span><b>${money(t.billed)}</b></div><div class="kpi"><span>Cobrado</span><b>${money(t.paid)}</b></div><div class="kpi"><span>Pendiente</span><b>${money(t.pending)}</b></div><div class="kpi"><span>Neto Caja</span><b>${money(t.net)}</b></div></div><div class="layout2" style="margin-top:18px"><div class="card"><h3>Actividad reciente</h3>${state.services.slice(-5).reverse().map(s=>`<p><b>${esc(s.code)}</b> ${esc(s.clientName)} · ${money(s.amount)}</p>`).join('')||'<p class="muted">Sin servicios.</p>'}</div><div class="card"><h3>Facturas pendientes</h3>${invoiceTable(state.invoices.filter(i=>i.balance>0).slice(0,6),false)}</div></div>`}
function renderClients(){$('clients').innerHTML=`<div class="layout2"><div class="card"><h3>Nuevo cliente</h3><div class="formrow"><input id="cName" placeholder="Nombre"><input id="cPhone" placeholder="Teléfono"><input id="cEmail" placeholder="Email"><input id="cAddr" placeholder="Dirección"><textarea id="cNotes" placeholder="Notas"></textarea><button class="btn primary" id="addClient">Guardar cliente</button></div></div><div class="card"><h3>Clientes</h3>${clientTable()}</div></div>`;$('addClient').onclick=()=>mutate(()=>{state.clients.push({id:uid(),name:$('cName').value,phone:$('cPhone').value,email:$('cEmail').value,address:$('cAddr').value,notes:$('cNotes').value,createdAt:new Date().toISOString()})})}
function clientTable(){return `<div class="tablewrap"><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Balance</th><th></th></tr></thead><tbody>${state.clients.map(c=>{const inv=state.invoices.filter(i=>i.clientId===c.id).reduce((a,i)=>a+Number(i.balance||0),0);return `<tr><td><b>${esc(c.name)}</b><br><span class="muted">${esc(c.address)}</span></td><td>${esc(c.phone)}<br>${esc(c.email)}</td><td class="money">${money(inv)}</td><td class="actions"><button class="btn tiny" onclick="NB.editClient('${c.id}')">Editar</button><button class="btn tiny danger" onclick="NB.delClient('${c.id}')">Borrar</button></td></tr>`}).join('')||'<tr><td colspan="4" class="muted">Sin clientes.</td></tr>'}</tbody></table></div>`}
function renderServices(){const L=labels();$('services').innerHTML=`<div class="layout2"><div class="card"><h3>Nuevo ${L.service}</h3><div class="formrow"><select id="sClient"><option value="">Cliente</option>${state.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><select id="sWorker"><option value="">${L.worker}</option>${state.team.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select><input id="sDate" type="date" value="${today()}"><input id="sTitle" placeholder="Descripción del servicio"><div class="grid2"><input id="sOrigin" placeholder="Origen / lugar"><input id="sDest" placeholder="Destino / detalle"></div><div class="grid3"><input id="sMiles" type="number" step="0.01" placeholder="Millas / cantidad"><input id="sRate" type="number" step="0.01" placeholder="Tarifa" value="0"><input id="sAmount" type="number" step="0.01" placeholder="Total"></div><textarea id="sNotes" placeholder="Notas"></textarea><button class="btn primary" id="addService">Guardar servicio</button></div></div><div class="card"><h3>${L.service}s</h3>${serviceTable()}</div></div>`;$('addService').onclick=()=>addService();['sMiles','sRate'].forEach(id=>$(id).oninput=()=>{const m=Number($('sMiles').value||0),r=Number($('sRate').value||0); if(m&&r)$('sAmount').value=(m*r).toFixed(2)})}
function addService(){mutate(()=>{const c=state.clients.find(x=>x.id===$('sClient').value),w=state.team.find(x=>x.id===$('sWorker').value);const code='SRV-'+String(state.settings.nextService++).padStart(5,'0');state.services.push({id:uid(),code,clientId:c?.id||'',clientName:c?.name||'',workerId:w?.id||'',workerName:w?.name||'',date:$('sDate').value,title:$('sTitle').value,origin:$('sOrigin').value,destination:$('sDest').value,miles:Number($('sMiles').value||0),rate:Number($('sRate').value||0),amount:Number($('sAmount').value||0),notes:$('sNotes').value,status:'completed'});})}
function serviceTable(){return `<div class="tablewrap"><table><thead><tr><th>ID</th><th>Cliente / Servicio</th><th>Equipo</th><th>Total</th><th></th></tr></thead><tbody>${state.services.map(s=>`<tr><td><b>${esc(s.code)}</b><br><span class="muted">${esc(s.date)}</span></td><td><b>${esc(s.clientName)}</b><br>${esc(s.title)}<br><span class="muted">${esc(s.origin)} → ${esc(s.destination)}</span></td><td>${esc(s.workerName)}</td><td class="money">${money(s.amount)}</td><td class="actions"><button class="btn tiny primary" onclick="NB.invoiceService('${s.id}')">Facturar</button><button class="btn tiny" onclick="NB.map('${s.id}')">Mapa</button><button class="btn tiny" onclick="NB.editMiles('${s.id}')">Millas</button><button class="btn tiny danger" onclick="NB.delService('${s.id}')">Borrar</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Sin servicios.</td></tr>'}</tbody></table></div>`}
function renderTeam(){const L=labels();$('team').innerHTML=`<div class="layout2"><div class="card"><h3>Nuevo ${L.worker}</h3><div class="formrow"><input id="wName" placeholder="Nombre"><input id="wPhone" placeholder="Teléfono"><div class="grid2"><input id="wCommission" type="number" step="0.01" placeholder="% comisión" value="60"><input id="wRetention" type="number" step="0.01" placeholder="% retención" value="10"></div><button class="btn primary" id="addWorker">Guardar</button></div></div><div class="card"><h3>${L.worker}s</h3>${workerTable()}</div></div>`;$('addWorker').onclick=()=>mutate(()=>state.team.push({id:uid(),name:$('wName').value,phone:$('wPhone').value,commission:Number($('wCommission').value||0),retention:Number($('wRetention').value||0),active:true}))}
function workerTable(){return `<div class="tablewrap"><table><thead><tr><th>Nombre</th><th>Servicios</th><th>Comisión</th><th>Retención</th><th>Balance</th><th></th></tr></thead><tbody>${state.team.map(w=>{const ss=state.services.filter(s=>s.workerId===w.id);const gross=ss.reduce((a,s)=>a+Number(s.amount||0)*Number(w.commission||0)/100,0);const ret=gross*Number(w.retention||0)/100;const paid=state.cashflow.filter(x=>x.workerId===w.id&&x.category==='Pago equipo').reduce((a,x)=>a+Number(x.amount||0),0);return `<tr><td><b>${esc(w.name)}</b><br>${esc(w.phone)}</td><td>${ss.length}</td><td>${money(gross)}</td><td>${money(ret)}</td><td class="money">${money(gross-ret-paid)}</td><td class="actions"><button class="btn tiny good" onclick="NB.payWorker('${w.id}')">Pagar</button><button class="btn tiny danger" onclick="NB.delWorker('${w.id}')">Borrar</button></td></tr>`}).join('')||'<tr><td colspan="6" class="muted">Sin equipo.</td></tr>'}</tbody></table></div>`}
function renderInvoices(){$('invoices').innerHTML=`<div class="card"><h3>Facturación</h3><p class="muted">Genera facturas desde Servicios. Cada factura queda conectada a cobros y caja.</p>${invoiceTable(state.invoices,true)}</div>`}
function invoiceTable(rows,actions=true){return `<div class="tablewrap"><table><thead><tr><th>Factura</th><th>Cliente</th><th>Total</th><th>Pagado</th><th>Balance</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(i=>`<tr><td><b>${esc(i.number)}</b><br><span class="pill ${i.balance<=0?'good':i.paid>0?'warn':'bad'}">${i.balance<=0?'Pagada':i.paid>0?'Parcial':'Pendiente'}</span></td><td>${esc(i.clientName)}<br><span class="muted">${esc(i.date)}</span></td><td class="money">${money(i.total)}</td><td>${money(i.paid)}</td><td class="money">${money(i.balance)}</td>${actions?`<td class="actions"><button class="btn tiny good" onclick="NB.quickPay('${i.id}')">Cobrar</button><button class="btn tiny" onclick="NB.pdfInvoice('${i.id}')">PDF</button><button class="btn tiny danger" onclick="NB.delInvoice('${i.id}')">Borrar</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${actions?6:5}" class="muted">Sin facturas.</td></tr>`}</tbody></table></div>`}
function renderPayments(){$('payments').innerHTML=`<div class="layout2"><div class="card"><h3>Registrar cobro</h3><div class="formrow"><select id="pInvoice"><option value="">Factura</option>${state.invoices.filter(i=>i.balance>0).map(i=>`<option value="${i.id}">${i.number} · ${esc(i.clientName)} · ${money(i.balance)}</option>`).join('')}</select><div class="grid2"><input id="pAmount" type="number" step="0.01" placeholder="Monto"><select id="pMethod"><option>ATH Móvil</option><option>Tarjeta</option><option>Transferencia</option><option>Efectivo</option><option>Cheque</option></select></div><button id="addPayment" class="btn primary">Registrar cobro</button></div></div><div class="card"><h3>Cobros</h3>${paymentTable()}</div></div>`;$('addPayment').onclick=()=>addPayment()}
function paymentTable(){return `<div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Factura</th><th>Método</th><th>Monto</th><th></th></tr></thead><tbody>${state.payments.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.invoiceNumber)}<br>${esc(p.clientName)}</td><td>${esc(p.method)}</td><td class="money">${money(p.amount)}</td><td><button class="btn tiny danger" onclick="NB.delPayment('${p.id}')">Borrar</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Sin cobros.</td></tr>'}</tbody></table></div>`}
function renderCashflow(){$('cashflow').innerHTML=`<div class="layout2"><div class="card"><h3>Movimiento de caja</h3><div class="formrow"><select id="cfType"><option value="income">Ingreso</option><option value="expense">Gasto</option></select><input id="cfCat" placeholder="Categoría"><input id="cfAmount" type="number" step="0.01" placeholder="Monto"><textarea id="cfNote" placeholder="Nota"></textarea><button id="addCf" class="btn primary">Guardar movimiento</button></div></div><div class="card"><h3>Flujo de Caja</h3>${cashTable()}</div></div>`;$('addCf').onclick=()=>mutate(()=>state.cashflow.push({id:uid(),date:today(),type:$('cfType').value,category:$('cfCat').value,amount:Number($('cfAmount').value||0),note:$('cfNote').value,manual:true}))}
function cashTable(){return `<div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Categoría</th><th>Monto</th><th>Nota</th><th></th></tr></thead><tbody>${state.cashflow.map(x=>`<tr><td>${esc(x.date)}</td><td><span class="pill ${x.type==='income'?'good':'bad'}">${x.type==='income'?'Ingreso':'Gasto'}</span></td><td>${esc(x.category)}</td><td class="money">${money(x.amount)}</td><td>${esc(x.note)}</td><td class="actions"><button class="btn tiny" onclick="NB.editCash('${x.id}')">Editar</button><button class="btn tiny danger" onclick="NB.delCash('${x.id}')">Borrar</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Sin movimientos.</td></tr>'}</tbody></table></div>`}
function renderReports(){$('reports').innerHTML=`<div class="card"><h3>Reportes PDF</h3><div class="grid3"><button class="btn primary" onclick="NB.pdfExecutive()">Reporte Ejecutivo</button><button class="btn" onclick="NB.pdfInvoices()">Reporte Facturas</button><button class="btn" onclick="NB.pdfTeam()">Reporte Equipo</button></div></div>`}
function renderPlans(){$('plans').innerHTML=`<div class="plans"><div class="plan"><h3>Starter</h3><div class="price">$0</div><ul><li>1 usuario</li><li>50 clientes</li><li>Reportes básicos</li></ul><button class="btn ghost" onclick="NB.setPlan('Starter')">Usar</button></div><div class="plan featured"><h3>Pro</h3><div class="price">$19.99</div><ul><li>Clientes ilimitados</li><li>PDF corporativo</li><li>Backup nube</li></ul><button class="btn primary" onclick="NB.setPlan('Pro')">Seleccionar</button></div><div class="plan"><h3>Business</h3><div class="price">$39.99</div><ul><li>Multiusuario futuro</li><li>WhatsApp/API futuro</li><li>Dashboard avanzado</li></ul><button class="btn ghost" onclick="NB.setPlan('Business')">Seleccionar</button></div></div>`}
function renderSettings(){$('settings').innerHTML=`<div class="layout2"><div class="card"><h3>Empresa</h3><div class="formrow"><input id="setName" value="${esc(state.company.name)}" placeholder="Empresa"><select id="setIndustry">${Object.keys(industryLabels).map(k=>`<option value="${k}" ${state.company.industry===k?'selected':''}>${esc(k)}</option>`).join('')}</select><input id="setPhone" value="${esc(state.company.phone)}" placeholder="Teléfono"><input id="setEmail" value="${esc(state.company.email)}" placeholder="Email"><input id="setAddress" value="${esc(state.company.address)}" placeholder="Dirección"><input id="setWeb" value="${esc(state.company.web)}" placeholder="Web"><input id="setRep" value="${esc(state.company.rep)}" placeholder="Representante"><input id="setTax" type="number" step="0.01" value="${state.company.taxRate}" placeholder="IVU %"><input id="logoInput" type="file" accept="image/*"><button id="saveSettings" class="btn primary">Guardar configuración</button><button id="resetAll" class="btn danger">Reset total</button></div></div><div class="card"><h3>Identidad</h3>${state.company.logo?`<img class="logoPreview" src="${state.company.logo}">`:''}<p><b>${esc(state.company.name)}</b></p><p class="muted">${esc(state.company.address)}<br>${esc(state.company.phone)} · ${esc(state.company.email)}</p></div></div>`;$('saveSettings').onclick=saveSettings;$('resetAll').onclick=()=>{if(confirm('Esto borra todos los datos de esta cuenta.'))mutate(()=>state=defaultState())};$('logoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>mutate(()=>state.company.logo=r.result);r.readAsDataURL(f)}}
function saveSettings(){mutate(()=>{state.company.name=$('setName').value;state.company.industry=$('setIndustry').value;state.company.phone=$('setPhone').value;state.company.email=$('setEmail').value;state.company.address=$('setAddress').value;state.company.web=$('setWeb').value;state.company.rep=$('setRep').value;state.company.taxRate=Number($('setTax').value||0)})}
function recalcInvoice(inv){const pays=state.payments.filter(p=>p.invoiceId===inv.id).reduce((a,p)=>a+Number(p.amount||0),0);inv.paid=pays;inv.balance=Math.max(0,Number(inv.total||0)-pays);inv.status=inv.balance<=0?'paid':pays>0?'partial':'pending'}
function addPayment(){mutate(()=>{const inv=state.invoices.find(i=>i.id===$('pInvoice').value);if(!inv)return;const amount=Number($('pAmount').value||0);const p={id:uid(),invoiceId:inv.id,invoiceNumber:inv.number,clientId:inv.clientId,clientName:inv.clientName,date:today(),amount,method:$('pMethod').value};state.payments.push(p);state.cashflow.push({id:uid(),date:p.date,type:'income',category:'Cobro factura',amount:p.amount,note:p.invoiceNumber,invoiceId:inv.id});recalcInvoice(inv);})}
function createInvoiceForService(serviceId){const s=state.services.find(x=>x.id===serviceId);if(!s)return toast('Servicio no encontrado');let inv=state.invoices.find(i=>i.serviceId===serviceId);if(inv)return toast('Este servicio ya tiene factura '+inv.number);mutate(()=>{const tax=Number(state.company.taxRate||0);const subtotal=Number(s.amount||0),taxAmt=+(subtotal*tax/100).toFixed(2),total=+(subtotal+taxAmt).toFixed(2);const number='INV-'+String(state.settings.nextInvoice++).padStart(5,'0');state.invoices.push({id:uid(),number,serviceId:s.id,serviceCode:s.code,clientId:s.clientId,clientName:s.clientName,date:today(),subtotal,tax:taxAmt,total,paid:0,balance:total,status:'pending',items:[{description:s.title||labels().service,qty:1,price:subtotal}]});});toast('Factura creada')}
function deletePayment(id){mutate(()=>{const p=state.payments.find(x=>x.id===id);state.payments=state.payments.filter(x=>x.id!==id);state.cashflow=state.cashflow.filter(x=>!(x.invoiceId===p?.invoiceId&&x.amount===p?.amount&&x.category==='Cobro factura'));state.invoices.forEach(recalcInvoice)})}
function pdfBase(title){const {jsPDF}=window.jspdf;const d=new jsPDF({unit:'pt',format:'letter'});let y=42;const W=d.internal.pageSize.getWidth(),c=W/2;if(state.company.logo){try{d.addImage(state.company.logo,'PNG',c-34,y,68,68);y+=78}catch{}}d.setFont('helvetica','bold');d.setFontSize(18);d.text(state.company.name||'Nexus Business PR',c,y,{align:'center'});y+=16;d.setFont('helvetica','normal');d.setFontSize(9);[state.company.address,state.company.phone,state.company.email,state.company.web].filter(Boolean).forEach(x=>{d.text(String(x),c,y,{align:'center'});y+=12});y+=14;d.setFont('helvetica','bold');d.setFontSize(16);d.text(title,c,y,{align:'center'});y+=26;return{d,y,W,c}}
function savePdf(d,name){d.save(name)}
function pdfInvoice(id){const inv=state.invoices.find(i=>i.id===id);if(!inv)return;const {d,W}=pdfBase('FACTURA');let y=190;d.setFontSize(10);d.setFont('helvetica','bold');d.text(`Factura: ${inv.number}`,42,y);d.text(`Fecha: ${inv.date}`,W-42,y,{align:'right'});y+=28;d.setFont('helvetica','normal');d.text(`Cliente: ${inv.clientName}`,42,y);y+=26;d.setFillColor(248,250,252);d.rect(42,y,W-84,24,'F');d.setFont('helvetica','bold');d.text('Descripción',52,y+16);d.text('Total',W-52,y+16,{align:'right'});y+=34;d.setFont('helvetica','normal');inv.items.forEach(it=>{d.text(String(it.description),52,y);d.text(money(it.price),W-52,y,{align:'right'});y+=20});y+=20;d.setFont('helvetica','bold');[['Subtotal',inv.subtotal],['IVU',inv.tax],['TOTAL',inv.total],['Pagado',inv.paid],['Balance',inv.balance]].forEach(r=>{d.text(r[0],W-180,y);d.text(money(r[1]),W-52,y,{align:'right'});y+=18});y+=50;d.line(80,y,240,y);d.line(W-240,y,W-80,y);y+=14;d.setFontSize(9);d.text('Cliente',160,y,{align:'center'});d.text('Representante Autorizado',W-160,y,{align:'center'});savePdf(d,`${inv.number}.pdf`)}
function pdfExecutive(){const t=totals();const {d,W}=pdfBase('REPORTE EJECUTIVO');let y=190;[['Clientes',t.clients],['Servicios',t.services],['Facturado',money(t.billed)],['Cobrado',money(t.paid)],['Pendiente',money(t.pending)],['Neto Caja',money(t.net)]].forEach(([a,b])=>{d.setFont('helvetica','bold');d.text(String(a),70,y);d.text(String(b),W-70,y,{align:'right'});y+=24});savePdf(d,'reporte-ejecutivo.pdf')}
function pdfInvoices(){const {d,W}=pdfBase('REPORTE DE FACTURAS');let y=190;state.invoices.forEach(i=>{d.setFontSize(9);d.text(`${i.number}  ${i.clientName}`,50,y);d.text(money(i.balance),W-50,y,{align:'right'});y+=18;if(y>720){d.addPage();y=50}});savePdf(d,'reporte-facturas.pdf')}
function pdfTeam(){const {d,W}=pdfBase('REPORTE DE EQUIPO');let y=190;state.team.forEach(w=>{const ss=state.services.filter(s=>s.workerId===w.id);const gross=ss.reduce((a,s)=>a+Number(s.amount||0)*Number(w.commission||0)/100,0);d.text(`${w.name} · Servicios: ${ss.length}`,50,y);d.text(money(gross),W-50,y,{align:'right'});y+=18});savePdf(d,'reporte-equipo.pdf')}
window.NB={editClient:id=>{const c=state.clients.find(x=>x.id===id);const n=prompt('Nombre',c.name);if(n!==null)mutate(()=>c.name=n)},delClient:id=>mutate(()=>state.clients=state.clients.filter(x=>x.id!==id)),delService:id=>mutate(()=>{state.services=state.services.filter(x=>x.id!==id);state.invoices=state.invoices.filter(i=>i.serviceId!==id)}),invoiceService:createInvoiceForService,map:id=>{const s=state.services.find(x=>x.id===id);window.open(`https://www.google.com/maps/dir/${encodeURIComponent(s.origin||'')}/${encodeURIComponent(s.destination||'')}`,'_blank')},editMiles:id=>{const s=state.services.find(x=>x.id===id);const m=prompt('Millas reales',s.miles);if(m!==null)mutate(()=>{s.miles=Number(m);s.amount=Number(s.rate||0)*s.miles;const inv=state.invoices.find(i=>i.serviceId===id);if(inv&&confirm('Actualizar factura con nuevas millas?')){inv.subtotal=s.amount;inv.tax=+(s.amount*Number(state.company.taxRate||0)/100).toFixed(2);inv.total=+(inv.subtotal+inv.tax).toFixed(2);recalcInvoice(inv)}})},delWorker:id=>mutate(()=>state.team=state.team.filter(x=>x.id!==id)),payWorker:id=>{const w=state.team.find(x=>x.id===id);const amount=Number(prompt('Monto a pagar a '+w.name,'0')||0);if(amount>0)mutate(()=>state.cashflow.push({id:uid(),date:today(),type:'expense',category:'Pago equipo',amount,workerId:id,note:w.name}))},quickPay:id=>{const inv=state.invoices.find(i=>i.id===id);const amount=Number(prompt('Monto cobrado',inv.balance)||0);if(amount>0)mutate(()=>{state.payments.push({id:uid(),invoiceId:id,invoiceNumber:inv.number,clientId:inv.clientId,clientName:inv.clientName,date:today(),amount,method:'Manual'});state.cashflow.push({id:uid(),date:today(),type:'income',category:'Cobro factura',amount,note:inv.number,invoiceId:id});recalcInvoice(inv)})},pdfInvoice,delInvoice:id=>mutate(()=>{state.invoices=state.invoices.filter(x=>x.id!==id);state.payments=state.payments.filter(x=>x.invoiceId!==id);state.cashflow=state.cashflow.filter(x=>x.invoiceId!==id)}),delPayment:deletePayment,editCash:id=>{const x=state.cashflow.find(a=>a.id===id);const a=prompt('Monto',x.amount);if(a!==null)mutate(()=>x.amount=Number(a))},delCash:id=>mutate(()=>state.cashflow=state.cashflow.filter(x=>x.id!==id)),pdfExecutive,pdfInvoices,pdfTeam,setPlan:p=>mutate(()=>state.company.plan=p)};
boot();
