import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, onSnapshot, collection, addDoc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const firebaseConfig = { apiKey:"AIzaSyDGoSNKi1wapE1SpHxTc8wNZGGkJ2nQj7s", authDomain:"nexus-transport-2887b.firebaseapp.com", projectId:"nexus-transport-2887b", storageBucket:"nexus-transport-2887b.firebasestorage.app", messagingSenderId:"972915419764", appId:"1:972915419764:web:7d61dfb03bbe56df867f21" };
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

const $ = id => document.getElementById(id);
const money = n => Number(n || 0).toLocaleString('en-US', { style:'currency', currency:'USD' });
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today = () => new Date().toISOString().slice(0,10);
const links = () => window.NEXUS_PAYMENT_LINKS || {};
const uid = () => auth.currentUser?.uid;

const COLS = ['clients','services','team','assets','suppliers','supplierPayments','payroll','invoices','payments','cashflow'];

const INDUSTRIES = {
  hvac:{name:'HVAC',logo:'HV',color:'#0ea5e9',client:'Cliente',clients:'Clientes',service:'Servicio HVAC',services:'Servicios HVAC',team:'Técnicos',payroll:'Nómina técnicos',assets:'Equipos',suppliers:'Suplidores HVAC',supplierPayments:'Pagos a suplidores',hero:'Diagnósticos, mantenimientos, garantías, facturas, nómina, suplidores y cobros.',nav:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],serviceFields:['Tipo de servicio','Equipo / Marca','BTU / Modelo','Diagnóstico','Garantía'],assetFields:['Marca','Modelo','BTU','Serial','Ubicación'],supplierFields:['Categoría','Marca principal','Términos','Notas']},
  salon:{name:'Salón / Barbería',logo:'SB',color:'#a855f7',client:'Cliente',clients:'Clientes',service:'Cita',services:'Agenda y Citas',team:'Estilistas',payroll:'Pagos estilistas',assets:'Estaciones',suppliers:'Suplidores belleza',supplierPayments:'Pagos a suplidores',hero:'Agenda, servicios de belleza, productos, comisiones, cobros y reportes.',nav:['dashboard','clients','services','team','payroll','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],serviceFields:['Servicio','Profesional','Hora','Duración','Notas de estilo'],assetFields:['Área','Silla / Estación','Estado','Notas'],supplierFields:['Categoría','Producto principal','Términos','Notas']},
  transport:{name:'Transporte',logo:'TR',color:'#2563eb',client:'Cliente',clients:'Clientes',service:'Servicio',services:'Servicios de Transporte',team:'Choferes',payroll:'Pagos a choferes',assets:'Flota',suppliers:'Suplidores / Talleres',supplierPayments:'Pagos a suplidores',hero:'Rutas, millas, facturación, cobros, comisiones, retenciones, flota y suplidores.',nav:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],serviceFields:['Origen','Destino','Millas reales','Tipo de carga','Evidencia'],assetFields:['Unidad','Tablilla','VIN','Marbete','Seguro'],supplierFields:['Categoría','Servicio principal','Términos','Notas']},
  handyman:{name:'Handyman',logo:'HM',color:'#f97316',client:'Cliente',clients:'Clientes',service:'Trabajo',services:'Trabajos',team:'Personal',payroll:'Pagos personal',assets:'Herramientas',suppliers:'Suplidores materiales',supplierPayments:'Pagos a suplidores',hero:'Trabajos livianos, materiales, evidencias, cobros, nómina y suplidores.',nav:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],serviceFields:['Categoría','Área','Materiales','Prioridad','Observaciones'],assetFields:['Herramienta','Estado','Costo','Asignado a'],supplierFields:['Categoría','Material principal','Términos','Notas']},
  cleaning:{name:'Limpieza',logo:'CL',color:'#14b8a6',client:'Cliente',clients:'Clientes',service:'Limpieza',services:'Servicios de Limpieza',team:'Personal',payroll:'Nómina personal',assets:'Inventario',suppliers:'Suplidores productos',supplierPayments:'Pagos a suplidores',hero:'Limpiezas residenciales/comerciales, productos, nómina, suplidores, cobros y reportes.',nav:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],serviceFields:['Tipo de limpieza','Área','Frecuencia','Productos','Notas'],assetFields:['Producto / Equipo','Cantidad','Costo','Ubicación'],supplierFields:['Categoría','Producto principal','Términos','Notas']},
  construction:{name:'Construcción',logo:'CO',color:'#64748b',client:'Cliente',clients:'Clientes',service:'Proyecto',services:'Proyectos',team:'Equipo',payroll:'Pagos de obra',assets:'Materiales / Equipo',suppliers:'Suplidores construcción',supplierPayments:'Pagos a suplidores',hero:'Proyectos, etapas, materiales, pagos de obra, suplidores, evidencias y reportes.',nav:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],serviceFields:['Tipo de proyecto','Dirección','Etapa','Materiales','Notas técnicas'],assetFields:['Material / Equipo','Cantidad','Costo','Proveedor'],supplierFields:['Categoría','Material principal','Términos','Notas']}
};

const PLANS = {
  free:{name:'Free',price:'$0',badge:'Básico',limits:{clients:5,services:10,team:1,assets:0,suppliers:0,supplierPayments:0,payroll:0,invoices:3,payments:3,cashflow:5},modules:['dashboard','clients','services','billing','plans','settings'],features:['5 clientes','10 servicios','3 facturas','Sin nómina','Sin suplidores','Sin reportes avanzados']},
  pro:{name:'Pro',price:'$19.99/mes',badge:'Profesional',limits:{clients:500,services:1000,team:10,assets:100,suppliers:25,supplierPayments:100,payroll:100,invoices:500,payments:500,cashflow:1000},modules:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],features:['Nómina básica','Suplidores','Logo en facturas','Reportes PDF','500 clientes']},
  business:{name:'Business',price:'$39.99/mes',badge:'Premium',limits:{clients:5000,services:10000,team:50,assets:1000,suppliers:500,supplierPayments:2000,payroll:2000,invoices:5000,payments:5000,cashflow:10000},modules:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],features:['White-label completo','Nómina avanzada','Control de suplidores','Firma digital','Reportes ejecutivos']},
  enterprise:{name:'Enterprise',price:'Custom',badge:'Corporativo',limits:{clients:Infinity,services:Infinity,team:Infinity,assets:Infinity,suppliers:Infinity,supplierPayments:Infinity,payroll:Infinity,invoices:Infinity,payments:Infinity,cashflow:Infinity},modules:['dashboard','clients','services','team','payroll','assets','suppliers','supplierPayments','billing','payments','cashflow','reports','plans','settings'],features:['Ilimitado','Dominio personalizado','Roles futuros','Soporte corporativo']}
};

const TITLES = {dashboard:'Dashboard',clients:'Clientes',services:'Servicios',team:'Equipo',payroll:'Nómina',assets:'Recursos',suppliers:'Suplidores',supplierPayments:'Pagos suplidores',billing:'Facturación',payments:'Cobros',cashflow:'Flujo de caja',reports:'Reportes',plans:'Planes',settings:'Configuración'};
let mode = 'login', unsub = [];
let state = {profile:null,clients:[],services:[],team:[],assets:[],suppliers:[],supplierPayments:[],payroll:[],invoices:[],payments:[],cashflow:[],previewHtml:'',activeView:'dashboard'};

function defaultProfile(){return {businessName:'Mi Negocio',industry:'hvac',plan:'free',phone:'',whatsapp:'',email:auth.currentUser?.email||'',address:'',web:'',tax:'11.5',merchant:'',representative:'',slogan:'',logoDashboard:'',logoPdf:'',favicon:'',signature:'',primaryColor:'#2563eb',secondaryColor:'#0f172a',createdAt:new Date().toISOString()};}
function profile(){return state.profile || defaultProfile();}
function industry(){return INDUSTRIES[profile().industry] || INDUSTRIES.hvac;}
function plan(){return PLANS[profile().plan] || PLANS.free;}
function colPath(c){return collection(db,'users',uid(),c);}
function docPath(c,id){return doc(db,'users',uid(),c,id);}
function profRef(){return doc(db,'users',uid());}
function limit(c){return plan().limits[c] ?? Infinity;}
function unlimited(v){return v === Infinity;}
function lockedModule(v){return !plan().modules.includes(v);}
function canCreate(c){const l=limit(c); return unlimited(l) || (state[c]||[]).length < l;}
function sum(a,k){return (a||[]).reduce((t,x)=>t+Number(x[k]||0),0);}
function teamBy(id){return state.team.find(x=>x.id===id)||{};}
function supplierBy(id){return state.suppliers.find(x=>x.id===id)||{};}
function invoiceBalance(inv){const paid=state.payments.filter(p=>p.invoiceId===inv.id).reduce((t,p)=>t+Number(p.amount||0),0);return Math.max(0,Number(inv.total||0)-paid);}
function teamCommission(tid){const t=teamBy(tid);return state.services.filter(s=>s.teamId===tid).reduce((a,s)=>a+(serviceAmount(s)*Number(t.rate||0)/100),0);}
function teamRetention(tid){const t=teamBy(tid);return state.services.filter(s=>s.teamId===tid).reduce((a,s)=>a+(serviceAmount(s)*Number(t.retention||0)/100),0);}
function payrollPaid(tid){return state.payroll.filter(p=>p.teamId===tid).reduce((a,p)=>a+Number(p.net||0),0);}
function teamBalance(tid){return Math.max(0,teamCommission(tid)-teamRetention(tid)-payrollPaid(tid));}
function supplierPaid(sid){return state.supplierPayments.filter(p=>p.supplierId===sid).reduce((a,p)=>a+Number(p.amount||0),0);}
function supplierBalance(sid){const s=supplierBy(sid);return Math.max(0,Number(s.openingBalance||0)-supplierPaid(sid));}
function imgOrText(data,text){return data?`<img src="${data}" alt="Logo">`:esc(text);}

function enforceModuleView(){const active=state.activeView||'dashboard';document.querySelectorAll('.main > section.view').forEach(view=>{const ok=view.id===active;view.classList.toggle('active',ok);view.hidden=!ok;view.setAttribute('aria-hidden',ok?'false':'true');view.style.display=ok?'block':'none';view.style.visibility=ok?'visible':'hidden';view.style.height=ok?'auto':'0px';view.style.overflow=ok?'visible':'hidden';});}
function show(v){state.activeView=lockedModule(v)?'plans':(v||'dashboard');render();if(innerWidth<921)document.querySelector('.sidebar')?.classList.remove('open');}
function setVisuals(){const p=profile(), ind=industry();document.documentElement.style.setProperty('--brand',p.primaryColor||ind.color);document.documentElement.style.setProperty('--brand2',p.secondaryColor||'#0f172a');$('sideLogo').innerHTML=imgOrText(p.logoDashboard,ind.logo);$('dashboardLogo').innerHTML=imgOrText(p.logoDashboard,ind.logo);$('authLogo').textContent=ind.logo;$('sideName').textContent=p.businessName||'Nexus Business';$('sideIndustry').textContent=ind.name;$('dashboardTitle').textContent=p.businessName||ind.name;$('dashboardText').textContent=p.slogan||ind.hero;$('faviconLink').href=p.favicon||$('faviconLink').href;$('planBadge').textContent=plan().name;$('sidePlan').innerHTML=plan().name;$('sideQuota').textContent=`${state.clients.length}/${unlimited(limit('clients'))?'∞':limit('clients')} clientes`;}
function nav(){const ind=industry();$('sideNav').innerHTML=ind.nav.map(v=>`<button type="button" data-view="${v}" class="${state.activeView===v?'active':''} ${lockedModule(v)?'locked':''}">${TITLES[v]||v}<span>${lockedModule(v)?'🔒':''}</span></button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));}
function input(label,id,type='text',val='',cls=''){return `<div class="${cls}"><label>${esc(label)}</label><input id="${id}" type="${type}" value="${esc(val)}" placeholder="${esc(label)}"></div>`;}
function select(label,id,opts,val='',cls=''){return `<div class="${cls}"><label>${esc(label)}</label><select id="${id}">${opts.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(val)?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div>`;}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${head.length}" class="muted">Sin registros.</td></tr>`}</tbody></table></div>`;}
function action(c,id){return `<div class="actions"><button data-edit="${c}:${id}" type="button">Editar</button><button class="danger" data-del="${c}:${id}" type="button">Borrar</button></div>`;}

function serviceTitle(s){
  return s?.title || (Array.isArray(s?.items) && s.items[0]?.description) || industry().service;
}
function serviceItemsTotal(items){
  return (items || []).reduce((a,it)=>a+(Number(it.qty||1)*Number(it.price||0)),0);
}
function serviceAmount(s){
  const itemsTotal = serviceItemsTotal(s.items || []);
  return itemsTotal > 0 ? itemsTotal : Number(s.amount || 0);
}
function itemRowsHtml(items){
  const arr = (items && items.length) ? items : [{description:'',qty:1,price:''}];
  return arr.map((it,idx)=>`<div class="service-line" data-service-line>
    <div class="line-number">${idx+1}</div>
    <input class="svc-desc" placeholder="Descripción del servicio / partida" value="${esc(it.description||'')}">
    <input class="svc-qty" type="number" step="0.01" min="0" placeholder="Cant." value="${esc(it.qty ?? 1)}">
    <input class="svc-price" type="number" step="0.01" min="0" placeholder="Precio" value="${esc(it.price ?? '')}">
    <button class="danger mini" data-remove-line type="button">×</button>
  </div>`).join('');
}
function getServiceItems(){
  return [...document.querySelectorAll('[data-service-line]')].map(row=>({
    description: row.querySelector('.svc-desc')?.value.trim() || '',
    qty: Number(row.querySelector('.svc-qty')?.value || 1),
    price: Number(row.querySelector('.svc-price')?.value || 0)
  })).filter(it=>it.description || it.price > 0);
}
function updateServiceTotal(){
  const total = serviceItemsTotal(getServiceItems());
  const amount = $('sAmount');
  const badge = $('sItemsTotal');
  if (badge) badge.textContent = money(total);
  if (amount && total > 0) amount.value = total.toFixed(2);
}
function bindServiceItems(){
  const addBtn = $('addServiceLine');
  if (!addBtn) return;
  addBtn.onclick = () => {
    const box = $('serviceItemsBox');
    box.insertAdjacentHTML('beforeend', itemRowsHtml([{description:'',qty:1,price:''}]));
    bindServiceItems();
    updateServiceTotal();
  };
  document.querySelectorAll('[data-remove-line]').forEach(btn=>btn.onclick=()=>{
    const rows = document.querySelectorAll('[data-service-line]');
    if(rows.length > 1) btn.closest('[data-service-line]').remove();
    else btn.closest('[data-service-line]').querySelectorAll('input').forEach((i,idx)=>i.value=idx===1?'1':'');
    updateServiceTotal();
  });
  document.querySelectorAll('.svc-desc,.svc-qty,.svc-price').forEach(el=>el.oninput=updateServiceTotal);
  updateServiceTotal();
}
function serviceItemsText(s){
  const items = s.items || [];
  if(items.length) return items.map(it=>`${it.qty || 1} × ${it.description || 'Servicio'} · ${money(it.price || 0)}`).join('<br>');
  return (s.fields||[]).map(esc).join(' · ');
}
function limitText(c){const l=limit(c);return unlimited(l)?`${(state[c]||[]).length}/∞`:`${(state[c]||[]).length}/${l}`;}
function limits(){['clients','services','team','assets','suppliers','supplierPayments','payroll','invoices','payments','cashflow'].forEach(c=>{const el=$(c+'Limit');if(el)el.textContent=`Uso: ${limitText(c)}`;});}

function forms(){const i=industry();
  $('clientsTitle').textContent=i.clients;$('servicesTitle').textContent=i.services;$('teamTitle').textContent=i.team;$('assetsTitle').textContent=i.assets;$('payrollTitle').textContent=i.payroll;$('suppliersTitle').textContent=i.suppliers;$('supplierPaymentsTitle').textContent=i.supplierPayments;
  $('clientForm').innerHTML=input('Nombre','cName')+input('Teléfono','cPhone')+input('Email','cEmail')+input('Municipio','cCity')+input('Dirección','cAddress','text','','wide')+'<button class="primary" type="submit">Guardar</button>';
  $('serviceForm').innerHTML=select(i.client,'sClient',state.clients.map(c=>({value:c.id,label:c.name})))+select(i.team,'sTeam',state.team.map(t=>({value:t.id,label:t.name})))+input('Fecha','sDate','date',today())+input('Descripción principal','sTitle','text','','wide')+input('Monto facturado','sAmount','number')+i.serviceFields.map((f,n)=>input(f,'sF'+n,'text','','wide')).join('')+`<div class="wide service-lines-card"><div class="line-head"><div><b>Servicios dentro de esta visita / factura</b><small class="muted">Añade varias partidas. El total se suma automáticamente.</small></div><strong id="sItemsTotal">$0.00</strong></div><div id="serviceItemsBox">${itemRowsHtml()}</div><button id="addServiceLine" class="ghost" type="button">+ Añadir otro servicio</button></div><button class="primary" type="submit">Guardar visita / servicio</button>`;
  $('teamForm').innerHTML=input('Nombre','tName')+input('Teléfono','tPhone')+input('Puesto / Rol','tRole')+input('% Comisión','tRate','number','0')+input('% Retención','tRetention','number','0')+'<button class="primary" type="submit">Guardar</button>';
  $('assetForm').innerHTML=i.assetFields.map((f,n)=>input(f,'aF'+n)).join('')+'<button class="primary" type="submit">Guardar</button>';
  $('supplierForm').innerHTML=input('Nombre suplidor','supName')+input('Teléfono','supPhone')+input('Email','supEmail')+input('Balance inicial / deuda','supOpening','number','0')+i.supplierFields.map((f,n)=>input(f,'supF'+n,'text','','wide')).join('')+'<button class="primary" type="submit">Guardar suplidor</button>';
  $('supplierPaymentForm').innerHTML=select('Suplidor','spSupplier',state.suppliers.map(s=>({value:s.id,label:`${s.name} · balance ${money(supplierBalance(s.id))}`})))+input('Fecha','spDate','date',today())+input('Método','spMethod','text','Transferencia')+input('Monto','spAmount','number')+input('Nota','spNote','text','','wide')+'<button class="primary" type="submit">Registrar pago</button>';
  $('payrollForm').innerHTML=select(i.team,'prTeam',state.team.map(t=>({value:t.id,label:`${t.name} · balance ${money(teamBalance(t.id))}`})))+input('Fecha','prDate','date',today())+input('Periodo','prPeriod','text')+input('Bruto','prGross','number')+input('Deducciones adicionales','prDeductions','number','0')+input('Método','prMethod','text','Transferencia')+input('Nota','prNote','text','','wide')+'<button class="primary" type="submit">Registrar pago de nómina</button>';
  $('paymentForm').innerHTML=select('Factura','pInvoice',state.invoices.map(inv=>({value:inv.id,label:`${inv.number} · ${inv.clientName} · balance ${money(invoiceBalance(inv))}`})))+input('Fecha','pDate','date',today())+input('Método','pMethod','text','ATH / Efectivo / Tarjeta')+input('Monto','pAmount','number')+input('Nota','pNote','text','','wide')+'<button class="primary" type="submit">Registrar cobro</button>';
  $('cashForm').innerHTML=input('Fecha','xDate','date',today())+select('Tipo','xType',[{value:'Ingreso',label:'Ingreso'},{value:'Gasto',label:'Gasto'}])+input('Concepto','xConcept')+input('Monto','xAmount','number')+'<button class="primary" type="submit">Guardar movimiento</button>';
  const p=profile();$('settingsForm').innerHTML=`<div><label>Industria</label><select id="set_industry">${Object.entries(INDUSTRIES).map(([id,x])=>`<option value="${id}" ${p.industry===id?'selected':''}>${x.name}</option>`).join('')}</select></div><div><label>Plan activo</label><select id="set_plan">${Object.entries(PLANS).map(([id,x])=>`<option value="${id}" ${p.plan===id?'selected':''}>${x.name}</option>`).join('')}</select><small class="muted">Producción: actualízalo por checkout/webhook o panel admin.</small></div>`+input('Nombre comercial','set_businessName','text',p.businessName)+input('Eslogan','set_slogan','text',p.slogan)+input('Teléfono','set_phone','text',p.phone)+input('WhatsApp','set_whatsapp','text',p.whatsapp)+input('Email','set_email','text',p.email)+input('Website','set_web','text',p.web)+input('Dirección','set_address','text',p.address,'wide')+input('Registro comerciante','set_merchant','text',p.merchant)+input('Representante','set_representative','text',p.representative)+input('IVU %','set_tax','number',p.tax)+input('Color primario','set_primaryColor','color',p.primaryColor)+input('Color secundario','set_secondaryColor','color',p.secondaryColor)+`<div><label>Logo Dashboard</label><input id="set_logoDashboard" type="file" accept="image/*"><small class="muted">Actual: ${p.logoDashboard?'cargado':'sin logo'}</small></div><div><label>Logo PDF</label><input id="set_logoPdf" type="file" accept="image/*"><small class="muted">Actual: ${p.logoPdf?'cargado':'sin logo'}</small></div><div><label>Favicon</label><input id="set_favicon" type="file" accept="image/*"><small class="muted">Actual: ${p.favicon?'cargado':'sin favicon'}</small></div><div><label>Firma digital</label><input id="set_signature" type="file" accept="image/*"><small class="muted">Actual: ${p.signature?'cargada':'sin firma'}</small></div>`;
  limits();
}

function kpis(){const billed=sum(state.invoices,'total'), collected=sum(state.payments,'amount'), expenses=state.cashflow.filter(x=>x.type==='Gasto').reduce((a,x)=>a+Number(x.amount||0),0), payroll=sum(state.payroll,'net'), supp=sum(state.supplierPayments,'amount');$('kpis').innerHTML=[['Clientes',state.clients.length],['Servicios',state.services.length],['Facturado',money(billed)],['Cobrado',money(collected)],['Nómina pagada',money(payroll)],['Suplidores pagados',money(supp)],['Gastos caja',money(expenses)],['Caja neta',money(collected-expenses)]].map(([a,b])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong></div>`).join('');$('planExperience').innerHTML=`<div class="experience"><b>${plan().badge}: ${plan().name}</b><span>${plan().features.join(' · ')}</span><div class="quota"><i style="width:${Math.min(100,(state.clients.length/(unlimited(limit('clients'))?Math.max(1,state.clients.length):limit('clients')))*100)}%"></i></div><button id="upgradeBtn" type="button">Ver planes</button></div>`;$('recentList').innerHTML=[...state.services.slice(-3).map(x=>`Servicio: ${x.clientName} · ${money(x.amount)}`),...state.payroll.slice(-2).map(x=>`Nómina: ${x.teamName} · ${money(x.net)}`),...state.supplierPayments.slice(-2).map(x=>`Suplidor: ${x.supplierName} · ${money(x.amount)}`)].map(x=>`<div class="list-item">${esc(x)}</div>`).join('')||'<p class="muted">Sin actividad.</p>'; $('upgradeBtn')&&($('upgradeBtn').onclick=()=>show('plans'));}

function tables(){const i=industry();
  $('clientsTable').innerHTML=table(['Nombre','Teléfono','Municipio','Acción'],state.clients.map(c=>`<tr><td><b>${esc(c.name)}</b><br><span class="muted">${esc(c.email)}</span></td><td>${esc(c.phone)}</td><td>${esc(c.city)}</td><td>${action('clients',c.id)}</td></tr>`));
  $('teamTable').innerHTML=table([i.team,'Comisión generada','Retención','Nómina pagada','Balance por pagar','Acción'],state.team.map(t=>`<tr><td><b>${esc(t.name)}</b><br><span class="muted">${esc(t.role)} · ${Number(t.rate||0)}% comisión</span></td><td>${money(teamCommission(t.id))}</td><td>${money(teamRetention(t.id))}</td><td>${money(payrollPaid(t.id))}</td><td><b>${money(teamBalance(t.id))}</b></td><td>${action('team',t.id)}</td></tr>`));
  $('payrollTable').innerHTML=table(['Fecha',i.team,'Periodo','Bruto','Deducciones','Neto','Método','Acción'],state.payroll.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.teamName)}</td><td>${esc(p.period)}</td><td>${money(p.gross)}</td><td>${money(p.deductions)}</td><td><b>${money(p.net)}</b></td><td>${esc(p.method)}</td><td>${action('payroll',p.id)}</td></tr>`));
  $('assetsTable').innerHTML=table(i.assetFields.concat('Acción'),state.assets.map(a=>`<tr>${(a.fields||[]).map(f=>`<td>${esc(f)}</td>`).join('')}<td>${action('assets',a.id)}</td></tr>`));
  $('suppliersTable').innerHTML=table(['Suplidor','Contacto','Balance inicial','Pagado','Balance','Acción'],state.suppliers.map(s=>`<tr><td><b>${esc(s.name)}</b><br><span class="muted">${(s.fields||[]).map(esc).join(' · ')}</span></td><td>${esc(s.phone)}<br><span class="muted">${esc(s.email)}</span></td><td>${money(s.openingBalance)}</td><td>${money(supplierPaid(s.id))}</td><td><b>${money(supplierBalance(s.id))}</b></td><td>${action('suppliers',s.id)}</td></tr>`));
  $('supplierPaymentsTable').innerHTML=table(['Fecha','Suplidor','Método','Monto','Nota','Acción'],state.supplierPayments.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.supplierName)}</td><td>${esc(p.method)}</td><td>${money(p.amount)}</td><td>${esc(p.note)}</td><td>${action('supplierPayments',p.id)}</td></tr>`));
  $('servicesTable').innerHTML=table(['ID','Fecha',i.client,i.team,'Detalle','Monto','Comisión','Factura','Acción'],state.services.map(s=>{const t=teamBy(s.teamId),inv=state.invoices.find(x=>x.serviceId===s.id),amount=serviceAmount(s),comm=amount*Number(t.rate||0)/100;return `<tr><td><code>${esc(String(s.id).slice(0,7))}</code></td><td>${esc(s.date)}</td><td>${esc(s.clientName)}</td><td>${esc(s.teamName)}</td><td><b>${esc(serviceTitle(s))}</b><br><span class="muted">${esc((s.fields||[]).filter(Boolean).slice(0,3).join(' · '))}</span></td><td>${money(amount)}</td><td>${money(comm)}</td><td>${inv?esc(inv.number):`<button data-invoice="${s.id}" type="button">Facturar</button>`}</td><td>${action('services',s.id)}</td></tr>`}));
  document.querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>createInvoice(b.dataset.invoice));
  $('invoiceTable').innerHTML=table(['Factura','Cliente','Servicio','Total','Pagado','Balance','Estado','Acción'],state.invoices.map(inv=>{const bal=invoiceBalance(inv),paid=Number(inv.total||0)-bal;return `<tr><td><b>${esc(inv.number)}</b></td><td>${esc(inv.clientName)}</td><td>${esc(inv.serviceTitle)}</td><td>${money(inv.total)}</td><td>${money(paid)}</td><td>${money(bal)}</td><td>${bal<=0?'Pagada':paid>0?'Parcial':'Pendiente'}</td><td><div class="actions"><button data-prev-inv="${inv.id}" type="button">Preview</button>${action('invoices',inv.id)}</div></td></tr>`}));
  document.querySelectorAll('[data-prev-inv]').forEach(b=>b.onclick=()=>previewInvoice(b.dataset.prevInv));
  $('paymentsTable').innerHTML=table(['Fecha','Factura','Método','Monto','Nota','Acción'],state.payments.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.invoiceNumber)}</td><td>${esc(p.method)}</td><td>${money(p.amount)}</td><td>${esc(p.note)}</td><td>${action('payments',p.id)}</td></tr>`));
  $('cashTable').innerHTML=table(['Fecha','Tipo','Concepto','Monto','Acción'],state.cashflow.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.type)}</td><td>${esc(x.concept)}</td><td>${money(x.amount)}</td><td>${action('cashflow',x.id)}</td></tr>`));
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(...b.dataset.del.split(':')));
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRecord(...b.dataset.edit.split(':')));
}

function plans(){$('plansGrid').innerHTML=Object.entries(PLANS).map(([id,p])=>`<div class="plan ${profile().plan===id?'featured':''}"><h3>${p.name}</h3><div class="price">${p.price}</div><p>${p.features.join('<br>')}</p><button type="button" data-plan="${id}" class="${profile().plan===id?'ghost':'primary'}">${profile().plan===id?'Plan activo':id==='free'?'Cambiar a Free':'Pagar / activar'}</button></div>`).join('');document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=async()=>{const id=b.dataset.plan;if(id!=='free'&&profile().plan!==id&&links()[id])window.open(links()[id],'_blank');await setDoc(profRef(),{...profile(),plan:id},{merge:true});});}
function render(){setVisuals();nav();forms();bindServiceItems();kpis();tables();plans();enforceModuleView();$('pageTitle').textContent=TITLES[state.activeView]||state.activeView;$('pageSubtitle').textContent=industry().hero;}
async function add(c,data){if(!canCreate(c)){alert(`Límite alcanzado en plan ${plan().name}. Mejora tu plan.`);show('plans');return null;}return await addDoc(colPath(c),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
async function remove(c,id){if(confirm('¿Borrar registro?'))await deleteDoc(docPath(c,id));}
async function editRecord(c,id){const arr=state[c]||[],r=arr.find(x=>x.id===id);if(!r)return;const val=prompt('Editar nombre/título/concepto principal:',r.name||r.title||r.concept||r.supplierName||r.teamName||'');if(val===null)return;const field=r.name!==undefined?'name':r.title!==undefined?'title':r.concept!==undefined?'concept':r.supplierName!==undefined?'supplierName':'teamName';await updateDoc(docPath(c,id),{[field]:val,updatedAt:serverTimestamp()});}
async function createInvoice(serviceId){if(!canCreate('invoices')){alert('Límite de facturas alcanzado.');show('plans');return;}const s=state.services.find(x=>x.id===serviceId);if(!s)return;const number='INV-'+String(Date.now()).slice(-7);await add('invoices',{number,date:today(),serviceId:s.id,clientId:s.clientId,clientName:s.clientName,serviceTitle:serviceTitle(s),items:s.items||[],fields:s.fields||[],total:serviceAmount(s),status:'Pendiente'});}
function docHeader(title){const p=profile(),logo=p.logoPdf||p.logoDashboard;return `<div class="doc-page"><div class="doc-body"><div class="doc-head">${logo?`<img class="doc-logo" src="${logo}">`:''}<div class="doc-title">${esc(p.businessName||'Empresa')}</div><div>${esc(p.address||'')}</div><div>${esc(p.phone||'')} ${p.email?' · '+esc(p.email):''} ${p.web?' · '+esc(p.web):''}</div><div>${p.merchant?'Registro: '+esc(p.merchant):''}</div></div><h2 style="text-align:center">${esc(title)}</h2>`;}
function docFooter(){const p=profile();return `</div><div class="doc-foot">${esc(p.businessName||'Empresa')}</div></div>`;}
function previewInvoice(id){const inv=state.invoices.find(x=>x.id===id);if(!inv)return;const bal=invoiceBalance(inv),paid=Number(inv.total||0)-bal;const rows=(inv.items&&inv.items.length)?inv.items.map(it=>`<tr><td>${esc(it.description||'Servicio')}</td><td>${esc(it.qty||1)}</td><td>${money(it.price||0)}</td><td>${money(Number(it.qty||1)*Number(it.price||0))}</td></tr>`).join(''):`<tr><td>${esc(inv.serviceTitle)}</td><td>1</td><td>${money(inv.total)}</td><td>${money(inv.total)}</td></tr>`;const html=docHeader('FACTURA')+`<div class="doc-meta"><div class="doc-box"><b>Factura:</b> ${esc(inv.number)}<br><b>Fecha:</b> ${esc(inv.date)}</div><div class="doc-box"><b>Cliente:</b> ${esc(inv.clientName)}<br><b>Estado:</b> ${bal<=0?'Pagada':paid>0?'Parcial':'Pendiente'}</div></div><table class="doc-table"><tr><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Total</th></tr>${rows}</table><div class="doc-total">Total: ${money(inv.total)}<br>Pagado: ${money(paid)}<br>Balance: ${money(bal)}</div>${profile().signature?`<p style="margin-top:35px"><img src="${profile().signature}" style="max-height:70px"><br>Firma autorizada</p>`:''}`+docFooter();state.previewHtml=html;$('reportPreview').innerHTML=html;show('reports');}
function preview(type){let title={executive:'REPORTE EJECUTIVO',invoices:'REPORTE DE FACTURAS',payments:'REPORTE DE COBROS',payroll:'REPORTE DE NÓMINA',suppliers:'REPORTE DE SUPLIDORES',services:'REPORTE DE SERVICIOS'}[type]||'REPORTE';let html=docHeader(title);if(type==='executive'){html+=`<table class="doc-table"><tr><th>Concepto</th><th>Total</th></tr><tr><td>Clientes</td><td>${state.clients.length}</td></tr><tr><td>Servicios</td><td>${state.services.length}</td></tr><tr><td>Facturado</td><td>${money(sum(state.invoices,'total'))}</td></tr><tr><td>Cobrado</td><td>${money(sum(state.payments,'amount'))}</td></tr><tr><td>Nómina pagada</td><td>${money(sum(state.payroll,'net'))}</td></tr><tr><td>Suplidores pagados</td><td>${money(sum(state.supplierPayments,'amount'))}</td></tr></table>`;}else if(type==='invoices'){html+=`<table class="doc-table"><tr><th>Factura</th><th>Cliente</th><th>Total</th><th>Balance</th></tr>${state.invoices.map(x=>`<tr><td>${esc(x.number)}</td><td>${esc(x.clientName)}</td><td>${money(x.total)}</td><td>${money(invoiceBalance(x))}</td></tr>`).join('')}</table>`;}else if(type==='payments'){html+=`<table class="doc-table"><tr><th>Fecha</th><th>Factura</th><th>Método</th><th>Monto</th></tr>${state.payments.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.invoiceNumber)}</td><td>${esc(x.method)}</td><td>${money(x.amount)}</td></tr>`).join('')}</table>`;}else if(type==='payroll'){html+=`<table class="doc-table"><tr><th>Fecha</th><th>Empleado</th><th>Periodo</th><th>Neto</th></tr>${state.payroll.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.teamName)}</td><td>${esc(x.period)}</td><td>${money(x.net)}</td></tr>`).join('')}</table>`;}else if(type==='suppliers'){html+=`<table class="doc-table"><tr><th>Suplidor</th><th>Balance inicial</th><th>Pagado</th><th>Balance</th></tr>${state.suppliers.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.openingBalance)}</td><td>${money(supplierPaid(x.id))}</td><td>${money(supplierBalance(x.id))}</td></tr>`).join('')}</table>`;}else{html+=`<table class="doc-table"><tr><th>Fecha</th><th>Cliente</th><th>Servicio</th><th>Monto</th></tr>${state.services.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.clientName)}</td><td>${esc(serviceTitle(x))}</td><td>${money(serviceAmount(x))}</td></tr>`).join('')}</table>`;}html+=docFooter();state.previewHtml=html;$('reportPreview').innerHTML=html;}
function fileData(input){return new Promise(res=>{const f=input?.files?.[0];if(!f)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f);});}
async function saveSettings(){const p={...profile()};['businessName','slogan','phone','whatsapp','email','web','address','merchant','representative','tax','primaryColor','secondaryColor'].forEach(k=>p[k]=$('set_'+k)?.value||'');p.industry=$('set_industry').value;p.plan=$('set_plan').value;for(const k of ['logoDashboard','logoPdf','favicon','signature']){const v=await fileData($('set_'+k));if(v)p[k]=v;}await setDoc(profRef(),p,{merge:true});alert('Configuración guardada.');}
function bindForms(){
  $('clientForm').onsubmit=e=>{e.preventDefault();add('clients',{name:$('cName').value,phone:$('cPhone').value,email:$('cEmail').value,city:$('cCity').value,address:$('cAddress').value});e.target.reset();};
  $('serviceForm').onsubmit=e=>{e.preventDefault();const c=state.clients.find(x=>x.id===$('sClient').value)||{},t=state.team.find(x=>x.id===$('sTeam').value)||{};const items=getServiceItems();const enteredTitle=($('sTitle')?.value||'').trim();const totalFromItems=serviceItemsTotal(items);const title=enteredTitle || items[0]?.description || industry().service;add('services',{clientId:c.id||'',clientName:c.name||'',teamId:t.id||'',teamName:t.name||'',date:$('sDate').value,title,amount:totalFromItems>0?totalFromItems:Number($('sAmount').value||0),items,fields:industry().serviceFields.map((_,n)=>$('sF'+n)?.value||'')});e.target.reset();bindServiceItems();};
  $('teamForm').onsubmit=e=>{e.preventDefault();add('team',{name:$('tName').value,phone:$('tPhone').value,rate:Number($('tRate').value||0),retention:Number($('tRetention').value||0),role:$('tRole').value});e.target.reset();};
  $('assetForm').onsubmit=e=>{e.preventDefault();add('assets',{fields:industry().assetFields.map((_,n)=>$('aF'+n)?.value||'')});e.target.reset();};
  $('supplierForm').onsubmit=e=>{e.preventDefault();add('suppliers',{name:$('supName').value,phone:$('supPhone').value,email:$('supEmail').value,openingBalance:Number($('supOpening').value||0),fields:industry().supplierFields.map((_,n)=>$('supF'+n)?.value||'')});e.target.reset();};
  $('supplierPaymentForm').onsubmit=e=>{e.preventDefault();const s=supplierBy($('spSupplier').value);if(!s.id)return alert('Selecciona suplidor.');const amount=Number($('spAmount').value||0);add('supplierPayments',{supplierId:s.id,supplierName:s.name,date:$('spDate').value,method:$('spMethod').value,amount,note:$('spNote').value});add('cashflow',{date:$('spDate').value,type:'Gasto',concept:`Pago suplidor ${s.name}`,amount});e.target.reset();};
  $('payrollForm').onsubmit=e=>{e.preventDefault();const t=teamBy($('prTeam').value);if(!t.id)return alert('Selecciona empleado/equipo.');const gross=Number($('prGross').value||0),ded=Number($('prDeductions').value||0),net=Math.max(0,gross-ded);add('payroll',{teamId:t.id,teamName:t.name,date:$('prDate').value,period:$('prPeriod').value,gross,deductions:ded,net,method:$('prMethod').value,note:$('prNote').value});add('cashflow',{date:$('prDate').value,type:'Gasto',concept:`Nómina ${t.name}`,amount:net});e.target.reset();};
  $('paymentForm').onsubmit=e=>{e.preventDefault();const inv=state.invoices.find(x=>x.id===$('pInvoice').value);if(!inv)return alert('Selecciona factura.');const amount=Number($('pAmount').value||0);add('payments',{invoiceId:inv.id,invoiceNumber:inv.number,date:$('pDate').value,method:$('pMethod').value,amount,note:$('pNote').value});add('cashflow',{date:$('pDate').value,type:'Ingreso',concept:`Cobro ${inv.number}`,amount});e.target.reset();};
  $('cashForm').onsubmit=e=>{e.preventDefault();add('cashflow',{date:$('xDate').value,type:$('xType').value,concept:$('xConcept').value,amount:Number($('xAmount').value||0)});e.target.reset();};
  $('saveSettings').onclick=saveSettings;$('invoiceFromService').onclick=()=>{const s=state.services.find(s=>!state.invoices.some(i=>i.serviceId===s.id));if(s)createInvoice(s.id);else alert('No hay servicios pendientes de facturar.');};
  document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{if(lockedModule('reports')){alert('Reportes es premium.');show('plans');return;}preview(b.dataset.preview);});
  $('printPreview').onclick=()=>{const html=state.previewHtml||$('reportPreview').innerHTML;const w=open('','_blank');w.document.write(`<html><head><title>Documento</title><link rel="stylesheet" href="styles.css"><style>@page{size:letter;margin:.45in;}html,body{margin:0!important;padding:0!important;background:#fff!important;}body{display:block!important;}.doc-page{width:100%!important;max-width:none!important;min-height:calc(11in - .9in)!important;margin:0!important;padding:0!important;border:0!important;box-shadow:none!important;transform:none!important;zoom:1!important;display:flex!important;flex-direction:column!important;}.doc-body{flex:1 1 auto!important;padding:0 0 .25in 0!important;}.doc-foot{position:static!important;margin-top:auto!important;text-align:center!important;}.doc-table{width:100%!important;}</style></head><body>${html}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print();},700);};
  $('downloadPreview').onclick=()=>{const {jsPDF}=window.jspdf;const docp=new jsPDF({unit:'pt',format:'a4'});docp.html(state.previewHtml||$('reportPreview').innerHTML,{callback:d=>{const pages=d.getNumberOfPages();for(let n=1;n<=pages;n++){d.setPage(n);d.setFontSize(8);d.setTextColor(100);d.text(`Página ${n} de ${pages}`,d.internal.pageSize.getWidth()/2,d.internal.pageSize.getHeight()-18,{align:'center'});}d.save('nexus-documento.pdf');},x:18,y:18,width:559,windowWidth:900,autoPaging:'text'});};
  $('sideUpgrade').onclick=()=>show('plans');$('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');$('logoutBtn').onclick=()=>signOut(auth);
}
function authUI(){$('authIndustry').innerHTML=Object.entries(INDUSTRIES).map(([id,x])=>`<option value="${id}">${x.name}</option>`).join('');$('showLogin').onclick=()=>{mode='login';document.querySelectorAll('.register-only').forEach(x=>x.classList.add('hidden'));$('authSubmit').textContent='Entrar';$('showLogin').classList.add('active');$('showRegister').classList.remove('active');};$('showRegister').onclick=()=>{mode='register';document.querySelectorAll('.register-only').forEach(x=>x.classList.remove('hidden'));$('authSubmit').textContent='Crear cuenta';$('showRegister').classList.add('active');$('showLogin').classList.remove('active');};$('authForm').onsubmit=async e=>{e.preventDefault();$('authMsg').textContent='Procesando...';try{if(mode==='register'){const cred=await createUserWithEmailAndPassword(auth,$('authEmail').value,$('authPassword').value);await setDoc(doc(db,'users',cred.user.uid),{...defaultProfile(),businessName:$('authBusiness').value||'Mi Negocio',industry:$('authIndustry').value,email:$('authEmail').value});}else await signInWithEmailAndPassword(auth,$('authEmail').value,$('authPassword').value);$('authMsg').textContent='';}catch(err){$('authMsg').textContent=err.message;}};}
async function load(){unsub.forEach(x=>x());unsub=[];const snap=await getDoc(profRef());if(!snap.exists())await setDoc(profRef(),defaultProfile());unsub.push(onSnapshot(profRef(),s=>{state.profile=s.data()||defaultProfile();render();}));COLS.forEach(c=>unsub.push(onSnapshot(colPath(c),s=>{state[c]=s.docs.map(d=>({id:d.id,...d.data()}));$('syncStatus').textContent='Sincronizado';render();},e=>{$('syncStatus').textContent='Firebase bloqueado';console.error(e);})));}
authUI();bindForms();onAuthStateChanged(auth,u=>{if(u){$('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');load();}else{$('authScreen').classList.remove('hidden');$('appShell').classList.add('hidden');}});
